In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('0.3pop-sfbay-fewer-bikes.gz.gz')
replanning = data[data['type'] == 'Replanning'].dropna(how='all', axis=1)
bikeReplanning = replanning[replanning['reason'].str.contains('BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('ResourceUnavailable BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('TRANSIT') == False]
display(bikeReplanning)

/usr/local/Cellar/jupyterlab/3.2.5/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0,4,5,19,21,22,23,24,25,31,33,34,35,36,43,45,47,49,53,54) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

             person     time        type                    reason
1665061   3023861.0  22594.0  Replanning  ResourceUnavailable BIKE
2399432     90247.0  23604.0  Replanning  ResourceUnavailable BIKE
3086517   1783594.0  24515.0  Replanning  ResourceUnavailable BIKE
3781800     12126.0  25243.0  Replanning  ResourceUnavailable BIKE
4298237    276543.0  25766.0  Replanning  ResourceUnavailable BIKE
...             ...      ...         ...                       ...
73201791  3797348.0  76924.0  Replanning  ResourceUnavailable BIKE
73451627  3430332.0  77151.0  Replanning  ResourceUnavailable BIKE
73572523  1070798.0  77260.0  Replanning  ResourceUnavailable BIKE
74389842  2813313.0  78163.0  Replanning  ResourceUnavailable BIKE
75471365    84355.0  79447.0  Replanning  ResourceUnavailable BIKE

[145 rows x 4 columns]

In [3]:
data = pd.read_csv('0.3pop-sfbay-more-bikes.gz')
replanning = data[data['type'] == 'Replanning'].dropna(how='all', axis=1)
bikeReplanning = replanning[replanning['reason'].str.contains('BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('ResourceUnavailable BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('TRANSIT') == False]
display(bikeReplanning)

/usr/local/Cellar/jupyterlab/3.2.5/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0,4,5,9,10,24,26,27,28,31,33,34,35,36,43,45,47,49,54,55) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

             person     time        type                    reason
407422    3027408.0  19344.0  Replanning  ResourceUnavailable BIKE
444048     432303.0  19415.0  Replanning  ResourceUnavailable BIKE
1734874   2979510.0  22659.0  Replanning  ResourceUnavailable BIKE
2424458   2975193.0  23656.0  Replanning  ResourceUnavailable BIKE
2467101   3297075.0  23624.0  Replanning  ResourceUnavailable BIKE
...             ...      ...         ...                       ...
78379892  2918154.0  83780.0  Replanning  ResourceUnavailable BIKE
78520144  4149278.0  84042.0  Replanning  ResourceUnavailable BIKE
79761743  2826687.0  86241.0  Replanning  ResourceUnavailable BIKE
83520061   479357.0  96718.0  Replanning  ResourceUnavailable BIKE
84243903  3688118.0  99093.0  Replanning  ResourceUnavailable BIKE

[468 rows x 4 columns]

In [4]:
data = pd.read_csv('0.3pop-sfbay-fewer-docks.gz')
replanning = data[data['type'] == 'Replanning'].dropna(how='all', axis=1)
bikeReplanning = replanning[replanning['reason'].str.contains('BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('ResourceUnavailable BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('TRANSIT') == False]
display(bikeReplanning)

/usr/local/Cellar/jupyterlab/3.2.5/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0,1,15,17,18,19,20,24,28,29,31,33,35,36,37,38,48,49,50,53) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

             time        type     person                    reason
387706    19206.0  Replanning  3090964.0  ResourceUnavailable BIKE
421578    19344.0  Replanning  3027408.0  ResourceUnavailable BIKE
439604    19429.0  Replanning  3056475.0  ResourceUnavailable BIKE
1087691   21516.0  Replanning  2837410.0  ResourceUnavailable BIKE
2020714   23037.0  Replanning  2865472.0  ResourceUnavailable BIKE
...           ...         ...        ...                       ...
74433119  78241.0  Replanning  2813313.0  ResourceUnavailable BIKE
77760758  82811.0  Replanning  2934368.0  ResourceUnavailable BIKE
77963861  83187.0  Replanning  3488011.0  ResourceUnavailable BIKE
78427062  83974.0  Replanning  2918154.0  ResourceUnavailable BIKE
79179065  85307.0  Replanning  3322953.0  ResourceUnavailable BIKE

[197 rows x 4 columns]

In [5]:
data = pd.read_csv('0.3pop-sfbay-more-docks.gz')
replanning = data[data['type'] == 'Replanning'].dropna(how='all', axis=1)
bikeReplanning = replanning[replanning['reason'].str.contains('BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('ResourceUnavailable BIKE')]
bikeReplanning = bikeReplanning[bikeReplanning['reason'].str.contains('TRANSIT') == False]
display(bikeReplanning)

/usr/local/Cellar/jupyterlab/3.2.5/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (0,4,5,22,24,25,26,27,28,31,33,34,35,36,43,45,47,49,53,56) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

             person     time        type                    reason
166824    4787196.0  18068.0  Replanning  ResourceUnavailable BIKE
167258    4804977.0  18072.0  Replanning  ResourceUnavailable BIKE
189602    2961042.0  18226.0  Replanning  ResourceUnavailable BIKE
189603     539378.0  18284.0  Replanning  ResourceUnavailable BIKE
189604    3409132.0  18298.0  Replanning  ResourceUnavailable BIKE
...             ...      ...         ...                       ...
75029298  3291880.0  78802.0  Replanning  ResourceUnavailable BIKE
75368682   467794.0  79185.0  Replanning  ResourceUnavailable BIKE
75926141  3219499.0  79905.0  Replanning  ResourceUnavailable BIKE
77266013  3690920.0  81847.0  Replanning  ResourceUnavailable BIKE
78946955  3728620.0  84759.0  Replanning  ResourceUnavailable BIKE

[369 rows x 4 columns]

In [6]:
data

,person,vehicle,time,type,vehicleType,links,numPassengers,length,primaryFuel,toStopIndex,...,personalVehicleAvailable,tourIndex,reason,score,departTime,cost,parkingZoneId,fuel,duration,shiftStatus
0,TransitDriverAgent-CC:31002002_merged_421003228,NaN,0.0,departure,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TransitDriverAgent-CC:31002002_merged_421003228,CC:31002002_merged_421003228,0.0,PersonEntersVehicle,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TransitDriverAgent-SF:7590302,NaN,0.0,departure,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TransitDriverAgent-SF:7590302,SF:7590302,0.0,PersonEntersVehicle,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TransitDriverAgent-3D:309,NaN,0.0,departure,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86616296,NaN,311868,108012.0,PathTraversal,sharedVehicle-sharedCar,"80516,80517",0.0,6540.156,2.391068e+07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86616297,NaN,311868,108012.0,ParkingEvent,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
86616298,2836562,NaN,108012.0,PersonCost,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86616299,2836562,311868,108012.0,PersonLeavesVehicle,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86616300,4163042,NaN,108000.0,ModeChoice,NaN,NaN,NaN,66185.001,NaN,NaN,...,True,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
pathTraversal = data[data['type'] == 'PathTraversal'].dropna(how='all', axis=1)

In [11]:
pathTraversal

,vehicle,time,type,vehicleType,links,numPassengers,length,primaryFuel,toStopIndex,fromStopIndex,...,capacity,arrivalTime,departureTime,linkTravelTime,secondaryFuel,secondaryFuelType,primaryFuelType,riders,mode,driver
85480,MA:5323312,42.0,PathTraversal,BUS-MA,"20393,134727,134715,17955,17951,132987,17949,7...",0.0,653.352,8.088759e+06,NaN,NaN,...,48.0,42.0,0.0,"10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,1...",0.0,None,Gasoline,NaN,bus,TransitDriverAgent-MA:5323312
85481,MA:5348932,42.0,PathTraversal,BUS-MA,"20393,134727,134715,17955,17951,132987,17949,7...",0.0,653.352,8.088759e+06,NaN,NaN,...,48.0,42.0,0.0,"10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,10.1,1...",0.0,None,Gasoline,NaN,bus,TransitDriverAgent-MA:5348932
149932,MA:5323312,300.0,PathTraversal,BUS-MA,"20389,16787,15697,15698,35152,35151,133091",0.0,1912.970,2.368333e+07,NaN,NaN,...,48.0,300.0,42.0,"29,29,29,29,29,29,0",0.0,None,Gasoline,NaN,bus,TransitDriverAgent-MA:5323312
149933,MA:5348932,300.0,PathTraversal,BUS-MA,"20389,16787,15697,15698,35152,35151,133091",0.0,1912.970,2.368333e+07,NaN,NaN,...,48.0,300.0,42.0,"29,29,29,29,29,29,0",0.0,None,Gasoline,NaN,bus,TransitDriverAgent-MA:5348932
149934,MA:5323327,698.0,PathTraversal,BUS-MA,"21450,133078",0.0,191.978,2.376764e+06,NaN,NaN,...,48.0,698.0,660.0,"23,0",0.0,None,Gasoline,NaN,bus,TransitDriverAgent-MA:5323327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86616278,1273818,108007.0,PathTraversal,conv-L1-0-to-50000-LowTech-2035-Car-ICEV_Gasoline,"63311,63310,63316,61005,60869,23947,23945,1346...",0.0,11809.028,1.831759e+07,NaN,NaN,...,3.0,108007.0,107579.0,"103.973,103.973,22.157,15.82,0.564,22.277,10.5...",0.0,None,Gasoline,NaN,car,6053956
86616283,4203880,108008.0,PathTraversal,conv-L1-0-to-50000-LowTech-2035-Car-ICEV_Gasoline,"68924,68927",0.0,8368.808,1.163132e+07,NaN,NaN,...,3.0,108008.0,107668.0,"35.521,340.373",0.0,None,Gasoline,NaN,car,2026525
86616290,2891389,108011.0,PathTraversal,sharedVehicle-sharedCar,"29136,29137,46176,46179,29261,76242,76241,4458...",0.0,18407.699,2.675651e+07,NaN,NaN,...,3.0,108011.0,107218.0,"4.938,4.938,2.024,117.955,3.456,23.062,11.87,5...",0.0,None,Gasoline,NaN,car,4759034
86616295,SF:7600910,108012.0,PathTraversal,BUS-DEFAULT,"140262,140178",0.0,19.199,3.849016e+05,NaN,NaN,...,57.0,108012.0,107990.0,"119,0",0.0,None,Diesel,NaN,bus,TransitDriverAgent-SF:7600910
86616296,311868,108012.0,PathTraversal,sharedVehicle-sharedCar,"80516,80517",0.0,6540.156,2.391068e+07,NaN,NaN,...,3.0,108012.0,107746.0,"265.999,265.999",0.0,None,Gasoline,NaN,car,2836562

In [12]:
pathTraversal['primaryFuelType'].unique()

array(['Gasoline', 'Diesel', 'Biodiesel', 'Electricity', 'Food'],
      dtype=object)